### ISSUE TITLE
Using pre-specified TADs by domaincaller

### ISSUE THREAD

**Issue by QianzhaoJ** [dozmorovlab/TADCompare#1]
Hi:
   I'm very interesting about this packages and I tried to find differential TAD boundaries between two datasets . I have called TAD boundaries using `domaincaller` .
   But when I typed 
`TAD_Compare = TADCompare(x, y, resolution = 10000, pre_tads = Combined_tad)`  and `x/y` readed using `HiCcompare::hicpro2bedpe` , the `TAD_Compare$TAD_Frame` showed 0 rows

> TAD_Compare$TAD_Frame
[1] Boundary     Gap_Score    TAD_Score1   TAD_Score2   Differential
[6] Enriched_In  Type        
<0 rows> (or 0-length row.names)
  
 I don't know what was wrong. Could you give me some suggestions ?

The format of `Combined_tad` :

> Combined_tad
[[1]]
        V1        V2        V3
  1: chr10     70000   1100000
  2: chr10   1130000   3110000
  3: chr10   3130000   3310000
  4: chr10   3310000   3820000
  5: chr10   3820000   4860000
....
[[2]]
        V1        V2        V3
  1: chr10     70000   1100000
  2: chr10   1130000   3130000
  3: chr10   3170000   3820000
  4: chr10   3820000   4860000
  5: chr10   4860000   5480000
....

**Comment by mdozmorov** [comment]
@QianzhaoJ, sorry for the delay replying. Try to put column names to your data, like the below. 
````
> Combined_tad
[[1]]
# A tibble: 1,044 x 4
   chr     start     end Level
   <chr>   <dbl>   <dbl> <dbl>
 1 chr1        0  480000     1
 2 chr1   480000 1000000     1
 3 chr1  1040000 1680000     1
 4 chr1  1680000 2200000     1
 5 chr1  2200000 2760000     1
 6 chr1  2760000 3040000     1
 7 chr1  3040000 3520000     1
 8 chr1  3520000 4000000     1
 9 chr1  4000000 4480000     1
10 chr1  4480000 5040000     1
# … with 1,034 more rows

[[2]]
# A tibble: 1,054 x 4
   chr     start     end Level
   <chr>   <dbl>   <dbl> <dbl>
 1 chr1        0  680000     1
 2 chr1   680000 1000000     1
 3 chr1  1040000 1680000     1
 4 chr1  2720000 3080000     1
 5 chr1  3080000 3520000     1
 6 chr1  3520000 3960000     1
 7 chr1  3960000 4440000     1
 8 chr1  4440000 4960000     1
 9 chr1  4960000 5480000     1
10 chr1  5480000 5840000     1
# … with 1,044 more rows
````

**Comment by mdozmorov** [comment]
Closed due to inactivity.

**Comment by ekokrek** [comment]
Thank you for this amazing tool. 
I have a similar problem, my TADs are from Arrowhead. 
As far as I can see, level information is not given in the arrowhead output. 

My Combined_bed file looks like:

```
> head(Combined_Bed)
[[1]]
# A tibble: 448 x 4
   chr       start       end Level
   <chr>     <int>     <int> <dbl>
 1 chr12  86420000  88390000     1
 2 chr12  60940000  62120000     1
 3 chr12  81840000  82740000     1
 4 chr12  33170000  34110000     1
 5 chr12   4950000   5950000     1
 6 chr12  13010000  14220000     1
 7 chr12  13410000  14320000     1
 8 chr12 128970000 130490000     1
 9 chr12  31440000  32380000     1
10 chr12  48100000  49070000     1
# … with 438 more rows

[[2]]
# A tibble: 546 x 4
   chr       start       end Level
   <chr>     <int>     <int> <dbl>
 1 chr12  58600000  59570000     1
 2 chr12 126370000 127910000     1
 3 chr12 118290000 120090000     1
 4 chr12 105660000 106610000     1
 5 chr12  31430000  32880000     1
 6 chr12  41340000  43790000     1
 7 chr12 120640000 122240000     1
 8 chr12 125630000 128410000     1
 9 chr12  53940000  54950000     1
10 chr12 101800000 103240000     1
# … with 536 more rows
```

I receive an empty TD_compare output as stated above.
Is level information obligatory? I created a dummy level column of 1's and then submitted it as input but result is still empty. 

Any suggestions would be appreciated.

**Comment by mdozmorov** [comment]
I'm not sure the question is relevant. TADCompare takes Hi-C matrices as an input. It doesn't take BED files from other TAD callers. Please, see the vignette, https://dozmorovlab.github.io/TADCompare/articles/TADCompare.html

**Comment by ekokrek** [comment]
It is 100% relevant.

from the vignette:
"We recognize that users may like to use their own TAD caller for the identification of TAD boundaries prior to boundary comparison. As a result, we provide the option for pre-specification of TADs in a form of two data frames with chromosome, start, and end coordinates of TAD boundaries for the two contact matrices. With this option, only provided TAD boundaries will be tested."

I didn't use the bed file directly. I created pre-defined TADs input as you describe in the vignette.
Above is the format of my Combined_bed file which is then submitted to the function along with nxn HiC matrices.

`TD_Compare <-  TADCompare(mtx1, mtx2, resolution = res, pre_tads = Combined_Bed)`

What I get is and empty result file with zero rows as @QianzhaoJ asked about.

**Comment by mdozmorov** [comment]
Your BED object is correct. The likely cause is that TADCompare cannot find any significant differences at Arrowhead-called boundaries. See [this plot](https://dozmorovlab.github.io/TADCompare/articles/TADCompare_files/figure-html/unnamed-chunk-10-1.png), how the boundary scores are compared. At Arrowhead boundaries, the boundary scores are not strong or different enough. Try setting `z_thresh = 1` or even lower.

**Comment by mdozmorov** [comment]
If you can share some subset of the data, I'll try to debug.

**Comment by ekokrek** [comment]
Thank you sir, 

I tried to reduce the z_thresh but result didn't change. 
As you suggested maybe no significant change could be found at Arrowhead boundaries, that is somehow expected in this case.
I just wanted to be sure if I can rely on the results.

Below are the files I used, sending you through google drive links. 

Thank you for your time! 

[mtx1](https://drive.google.com/file/d/1co_gEn7bXzAhiLTKl38ZXZeN8ncecibH/view?usp=sharing)
[mtx2](https://drive.google.com/file/d/1vcj8DIva7CNegC1gvLGx5IuwYofgPlEE/view?usp=sharing)
[combined_bed](https://drive.google.com/file/d/1F5lAvgh735uOwK9i6-P3F8C5JSEfhXfk/view?usp=sharing)

**Comment by mdozmorov** [comment]
Arrowhead domains are very large and indeed do not overlap with boundary scores. We observed it as well. Otherwise, differential boundaries detected using boundary score are as expected, see`$Boundary_Scores` slot. That's what I use, but if you absolutely need to use Arrowhead domains, then the best way is to avoid TADCompare altogether and simply intersect Arrowhead boundaries. 

Here is the code I used.

```{r}
load("~/Downloads/mtx1.Rdata")
load("~/Downloads/mtx2.Rdata")
load("~/Downloads/combBed.Rdata")
image(mat1[1:300, 1:300])
image(mat2[1:300, 1:300])
Combined_Bed
TD_Compare1 <- TADCompare(mat1, mat2, pre_tads = Combined_Bed, z_thresh = 3)
TD_Compare1

mtx1 <- mat1
mtx2 <- mat2
res <- 10000 # Set resolution
# Globally normalize matrices for better visual comparison (does not affect TAD calling)
mtx1_total <- sum(mtx1)
mtx2_total <- sum(mtx2)
(scaling_factor <- mtx1_total / mtx2_total)

if (mtx1_total > mtx2_total) {
  mtx2 <- mtx2 * scaling_factor
} else {
  mtx1 <- mtx1 * (1 / scaling_factor)
}
# Coordinates of interesting regions
start_coord <- 8000000
end_coord   <- 12000000

p <- DiffPlot(tad_diff    = TD_Compare1, 
              cont_mat1   = mtx1,
              cont_mat2   = mtx2,
              resolution  = res,
              start_coord = start_coord,
              end_coord   = end_coord,
              show_types  = FALSE, 
              point_size  = 5,
              max_height  = 100,
              rel_heights = c(1, 2),
              palette     = "RdYlBu")
plot(p)
```

**Comment by ekokrek** [comment]
Thank you very much sir, 
for the quick reply and help.
