### ISSUE TITLE
Getting coordinates of split/merged tads

### ISSUE THREAD

**Issue by nyuhic** [dozmorovlab/TADCompare#10]
Hello,

The results dataframe classifies tad boundaries as split, merged or non-differential.  I was wondering how I can extract the coordinates of the actual tad that was split or merged in the treatment condition (matrix 1) vs the control condition (matrix 2)? Would it be just the boundaries immediately preceding and following the split/merged boundary in the results$TAD_frame? Is there a way I can extract those?

Thanks

**Comment by mdozmorov** [comment]
Hi @nyuhic, we touched on this in the paper.  TADcompare focuses on boundary changes, and that's what it returns. You can assume that the actual TADs formed by those boundaries are continuous. You can extract coordinates of all boundaries from `results$Boundary_Scores` and plot them on the linear genome. So, two adjacent "Non-differential" boundaries will correspond to a TAD present in both conditions. "Non-differential"-"Differential"-"Non-differential" - the middle boundary changed in one condition. We provided an option to pre-specify TADs, but that'll defy the purpose of TADcompare. Again, TADcompare focuses on changes in boundaries. Hope that helps.

**Comment by nyuhic** [comment]
Thanks for the quick response. Would appreciate if you can clarify one more point. As you mentioned I can extract the coordinates of  boundaries from results$Boundary_Scores. My understanding was that this dataframe contains the score of every genomic bin irrespective of whether it is a tad boundary or not. So to get tad boundaries shouldn't I extract the coordinates from results$TAD_frame? As you said the tad would span the two non-differential boundaries on either side of the differential one.
(just to clarify, the purpose of my analysis is to see how the splitting/merging of a tad affects the expression of genes located in it for which I am extracting the tad coordinates.) 

Thanks

**Comment by mdozmorov** [comment]
Yes, the actual boundaries should be extracted from `results$TAD_Frame`.  Consider "Non-Differential" boundaries as present in both conditions. And "Differential" - boundaries that were detected in one condition only.

**Comment by nyuhic** [comment]
Thanks
