### ISSUE TITLE
The  TADCompare vignette link directs to a 404 error page; not the vignette

### ISSUE THREAD

**Issue by KTMD-plant** [dozmorovlab/TADCompare#11]

**Comment by mdozmorov** [comment]
Thanks, @KTMD-plant, for noticing. It should be fixed now. The [website](https://dozmorovlab.github.io/TADCompare/articles/TADCompare.html) and the Bioconductor vignettes are functional.
https://www.bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/Input_Data.html
https://www.bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/TADCompare.html
https://www.bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/Ontology_Analysis.html

**Comment by KTMD-plant** [comment]
No worries! Thanks for the quick response!
