### ISSUE TITLE
Ontology Analysis vignette link not functional

### ISSUE THREAD

**Issue by TerezaClarence** [dozmorovlab/TADCompare#12]
Dear TADCompare developers,

thank you for developing such an amazing tool! I was wondering whether there is any other link to the Ontology and pathway enrichment analysis? The link here on github for the Ontology pathway is not working.

Thank you very much.

Best regards,
Tereza

**Comment by mdozmorov** [comment]
Thank you, Theresa, for noticing this. All vignettes are rendered on the Bioconductor page of TADcompare, https://bioconductor.org/packages/TADCompare/. Including the [Gene Ontology Enrichment Analysis](https://bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/Ontology_Analysis.html) vignette. I updated the links in the README.

**Comment by TerezaClarence** [comment]
Thank you so much for your help. I am sorry to be bothering again but is there a simple way how to change/use a different reference genome within the rGREAT? for instance hg38 instead of hg19?

Thank you,
Tereza

**Comment by TerezaClarence** [comment]
Actually, I found out it can be changed easily as suggested here: https://github.com/jokergoo/rGREAT however 'hg38' is not available as they wrote, only hg18 or hg19 for current versions,..
