### ISSUE TITLE
Suggestion for analysis - dealing with replicates

### ISSUE THREAD

**Issue by TerezaClarence** [dozmorovlab/TADCompare#13]
Dear TADCompare developers,

I would like to ask for your opinion; I am dealing with large HiC dataset and I have multiple replicates for for each celltype (and timepoint). Is it possible to generate Consensus TADs on each cell type (from several replicates) and then run pairwise TADCompare on ConsensusTAD_celltype1 vs ConsensusTAD_celltype2 objects?

Also, is it possible to do the same thing for TimeCompare? Compare consensusTAD objects for multiple timepoints rather that have a single Hi-C data for each time point? (Again, I have multiple replicates for each timepoint).

Thank you for your suggestions!

Best,
Tereza

**Comment by mdozmorov** [comment]
It is possible to [call consensus TADs](https://www.bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/TADCompare.html#consensustads) and [prespecify them for TADcompare](https://www.bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/TADCompare.html#pre-specification-of-tads). The only problem is that TADcompare requires a pair of Hi-C matrices and it is unclear which ones to use. For time-course, no, it works with one matrix per time point. 

These are great case scenarios we need to work on.
