### ISSUE TITLE
multiple samples TADs(consensusTADs)

### ISSUE THREAD

**Issue by DittmanC** [dozmorovlab/TADCompare#14]
Is there any software/tools that can visualize the findings from ConsensusTADs?

**Comment by mdozmorov** [comment]
We've visualized several matrices and TADs using [HiCExplorer](https://hicexplorer.readthedocs.io/en/latest/content/tools/hicPlotTADs.html)/[pygenometracks](https://github.com/deeptools/pyGenomeTracks) and [CoolBox](https://github.com/GangCaoLab/CoolBox).

Improving visualization within the package is on my list. Help wanted!
