### ISSUE TITLE
Status of TADCompare on Bioconductor builders

### ISSUE THREAD

**Issue by Kayla-Morrell** [dozmorovlab/TADCompare#15]
I wanted to touch base with you about the current state of ‘TADCompare’ on the Bioconductor builders. I tried to send an email to the maintainer email address listed in the DESCRIPTION file but it came back as undeliverable so I figured I'd try opening an issue. ‘TADCompare’ is failing across all 3 platforms in both the release and devel versions of Bioconductor. The error seems to be coming from a vignette that won’t build.
 
Release build report – https://bioconductor.org/checkResults/3.16/bioc-LATEST/TADCompare/
Devel build report – https://bioconductor.org/checkResults/3.17/bioc-LATEST/TADCompare/
 
Could you please address the issue at your earliest convenience? Thanks!

**Comment by mdozmorov** [comment]
It may be time to deprecate this package. Some dependency has changed (likely, [PRIMME](https://cran.r-project.org/package=PRIMME)) and this broke TADCompare and SpectralTAD packages. I tried to fix them, but practically out of capacity. I will keep trying, or deprecate before the next BioC release.
