### ISSUE TITLE
differential TADs

### ISSUE THREAD

**Issue by benxiahu** [dozmorovlab/TADCompare#2]
Hi,
    I know TADCompare can identify differential TADs between 2 samles.
   I also want to know whether it can identify differential TADs among 3 samples?
Best,

**Comment by mdozmorov** [comment]
Yes, TADCompare works with more than two conditions. @benxiahu, please, review the [paper](https://www.frontiersin.org/articles/10.3389/fgene.2020.00158/full) describing timecourse analysis. But it requires four samples (time points), or more.

For three samples, I suggest selecting a reference sample, performing pairwise comparisons against it, and then look for consistent differences.
