### ISSUE TITLE
About Diffplot.

### ISSUE THREAD

**Issue by junjunxy** [dozmorovlab/TADCompare#20]
Hi, I am analyzing Hi-C data generated using TADCompare.

I converted .cool file to .txt file using cooler, and performed downstream analysis. 

I was able to do most of the analysis, except the visualization with pre-defined tad. 

Could you help me to moving forward? 

This is my whole code

---

library(dplyr)
library(SpectralTAD)
library(TADCompare)

cool_mat1_TT <- read.table("/Users/bin/cooler/TT20.20K.txt")
cool_mat2_CC <- read.table("/Users/bin/cooler/CC03.20K.txt")

sparse_mat1_TT <- HiCcompare::cooler2sparse(cool_mat1_TT)
sparse_mat1_CC <- HiCcompare::cooler2sparse(cool_mat2_CC)

selected_sparse_mat1_TT <- lapply(sparse_mat1_TT[1:29], function(x) x)
selected_sparse_mat1_CC <- lapply(sparse_mat1_CC[1:29], function(x) x)

diff_tads = lapply(names(selected_sparse_mat1_TT), function(x) {
  TADCompare(selected_sparse_mat1_TT[[x]], selected_sparse_mat1_CC[[x]], resolution = 20000)
})

head(diff_tads)
head(diff_tads[[14]][["TAD_Frame"]])
head(diff_tads[[14]][["Count_Plot"]][["data"]])

View(diff_tads[[14]][["TAD_Frame"]])

DiffPlot(tad_diff    = diff_tads[[14]], 
         cont_mat1   = selected_sparse_mat1_TT[[14]],
         cont_mat2   = selected_sparse_mat1_CC[[14]],
         resolution  = 20000,
         start_coord = 49720000,
         end_coord   = 51400000,
         show_types  = TRUE, 
         point_size  = 5,
         palette     = "RdYlBu",
         rel_heights = c(1, 2))

tad_TT = SpectralTAD(selected_sparse_mat1_TT[[14]], chr = "14", levels = 3, qual_filter = FALSE)
tad_CC = SpectralTAD(selected_sparse_mat1_CC[[14]], chr = "14", levels = 3, qual_filter = FALSE)
Combined_Bed = list(tad_TT, tad_CC)

TD_Compare <- TADCompare(selected_sparse_mat1_TT[[14]], selected_sparse_mat1_CC[[14]], resolution = 20000, pre_tads = Combined_Bed)

---
Error

> tad_TT = SpectralTAD(selected_sparse_mat1_TT[[14]], chr = "14", levels = 3, qual_filter = FALSE)
Converting to n x n matrix
Matrix dimensions: 5098x5098
Estimating resolution
> tad_CC = SpectralTAD(selected_sparse_mat1_CC[[14]], chr = "14", levels = 3, qual_filter = FALSE)
Converting to n x n matrix
Matrix dimensions: 5097x5097
Estimating resolution
> Combined_Bed = list(tad_TT, tad_CC)
> TD_Compare <- TADCompare(selected_sparse_mat1_TT[[14]], selected_sparse_mat1_CC[[14]], resolution = 20000, pre_tads = Combined_Bed)
Converting to n x n matrix
Matrix dimensions: 5098x5098
Matrix dimensions: 5097x5097
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 396, 376, 366

Thank you in advance 😃

**Comment by mdozmorov** [comment]
Hi @junjunxy. Judging by the error alone, it suggests your matrices are of different dimensions. This may happen because of missing values at telomeres. Check the dimensions and make the matrices similar/parallel, so each row correspond to the same genomic coordinate. Two ways of doing that - either fill in the missing rows/columns (with zeros or other methods - that's a separate question), or remove the extra rows/columns in another matrix. How to do it - depends on the data format.

As for visualization, we'd recommend https://github.com/deeptools/HiCExplorer, it has functions to visualize matrices and TADs.

**Comment by junjunxy** [comment]
Thanks for your advice :) I managed to visualize the matrices using hicExplorer.
