### ISSUE TITLE
How to use TADCompare on ConsensusTADs output

### ISSUE THREAD

**Issue by Rohit-Satyam** [dozmorovlab/TADCompare#22]
I have data from the ctrl vs KO Hi-C experiment. For both ctrl and KO samples I have two biological replicates
I was planning to combine the biological replicates (both for ctrls and KO separately) and then using the resulting matrix to run Differential TAD analysis. For some reason I couldn't find in the vignette, how to do that. Can you kindly help me here?

**Comment by mdozmorov** [comment]
It is unclear how the replicates were combined. If with ConsensusTAD, we don't have functionality for downstream differential analysis. I suggest combining matrices first (sum them up) and then proceed with the standard comparison of two matrices.

**Comment by Rohit-Satyam** [comment]
@mdozmorov Yes I was using ConsensusTAD in the hope that it will combine the Replicates. I couldn't find an R package or other command line utility that performs differential TAD analysis using replicates. I found out [here](https://cran.r-project.org/web/packages/chicane/vignettes/Getting_Started.html#merging-biological-replicates) that based on how good your biological replicates agree with each other you can either sum counts or use weighted sum so rightnow I am using something like the code below:

```
## looping for all the chromosomes
ctrl16 <- lapply(1:14, function(x){
  #ConsensusTADs(list(p16hpi.rep2[[x]],p16hpi.rep1[[x]]), resolution = 50000)
  bind_rows(p16hpi.rep2[[x]],p16hpi.rep1[[x]]) %>% group_by(x,y) %>% summarise(counts = sum(counts), .groups = 'drop') 
  })
```

**Comment by mdozmorov** [comment]
This may help, https://stackoverflow.com/questions/14147655/is-there-an-r-function-for-the-element-wise-summation-of-the-matrices-stored-as. And, we have some code to check replicate similarity with HiCrep, https://github.com/dozmorovlab/PDXHiC_supplemental/tree/main/Fig4_HiC_misc

**Comment by Rohit-Satyam** [comment]
Thanks for the references above. Will check them out. I have another query before I close this issue

For the following results:

```r
$TAD_Frame
  Boundary   Gap_Score TAD_Score1 TAD_Score2     Differential Enriched_In             Type
1   400000 -2.35384176   2.521042   2.666664     Differential    Matrix 2  Strength Change
2   450000 -0.02039092   2.097731   1.995984 Non-Differential    Matrix 2 Non-Differential
3   550000 -0.30488579   1.637665   1.591467 Non-Differential    Matrix 2 Non-Differential
4  1100000 -1.84786257   2.712948   2.790854 Non-Differential    Matrix 2 Non-Differential
5  1850000 -2.13553438   1.791960   1.948652     Differential    Matrix 2  Strength Change
6  1900000 -1.42710550   1.721279   1.800001             <NA>    Matrix 2             <NA>
```
Where does the `Type` Strength Change starts and ends? Is it from `350000 to 400000` or from `400000 to 450000` and why Non-DIfferential sites are in TAD_Frame even when they have `Gap_Score` score less than `abs(2)`

**Comment by mdozmorov** [comment]
Boundary start coordinates are listed. The region of strength change is start + resolution. So, if resolution is 50K, the first boundary with strength change is from 400000 to 450000
