### ISSUE TITLE
Issue with Nested Triangles in DiffPlot Visualization

### ISSUE THREAD

**Issue by yyh-1211** [dozmorovlab/TADCompare#24]
Dear TADcompare Developers,

I have encountered an issue when visualizing the TAD boundaries using the DiffPlot function in TADcompare. Specifically, I notice that in some cases, large triangles are nested with smaller triangles within them, which seems to represent nested TAD regions.

Could you help me understand why this is happening? Is this expected behavior when there are nested TAD boundaries, or could it be related to the way the TAD boundaries are being defined or visualized in my input data?

For context, I am using pre-specified TADs for comparison between two contact matrices. Both matrices have TAD boundaries defined with a resolution of 10kb. When I run the DiffPlot function, I see that the TAD regions are sometimes represented by a larger triangle containing smaller ones, even though the boundaries are clearly defined. The visualization of large triangles containing smaller triangles looks like the image below.

Any insight into why this happens and how to address or adjust the visualization to avoid this nested triangle issue would be greatly appreciated!

Thank you for your help!

Best regards,
yyh
![1](https://github.com/user-attachments/assets/8d2f00eb-012d-491c-9ab0-236c1b005b2b)

**Comment by mdozmorov** [comment]
Hi @yyh-1211 , what you showing looks correct. Note in the [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/TADCompare/inst/doc/TADCompare.html#comparing-pre-defined-tad-boundaries) that pre-defined boundaries are used by `TADCompare` to call TADs.
```
# Running TADCompare with pre-specified TADs
TD_Compare <-  TADCompare(mtx1, mtx2, resolution = res, pre_tads = Combined_Bed)
```

TADCompare uses SpectralTAD to call hierarchical TADs on the predefined boundaries. In your case, it defines some nested TADs around the boundaries you provided. And the corresponding differences, which are the most important. You can ignore  the nested triangles and use coordinates of the different types of differential boundaries. You can also use other visualization tools, like https://github.com/deeptools/pyGenomeTracks, that give you more control what you want to visualize.

**Comment by yyh-1211** [comment]
Okay, I understand now. Thank you very much for your reply.
