### ISSUE TITLE
Puzzled about the results of TADCompare.

### ISSUE THREAD

**Issue by esroom** [dozmorovlab/TADCompare#6]
Hi,  I'm a little confused about the results of the **TADCompare** function. I got the results like this.
![image](https://user-images.githubusercontent.com/44914876/100492030-966a3c00-3163-11eb-88f0-0154aea86ded.png)
What is the difference between the **_Differential_**  and   **_Type_** columns?  Could I  pick **Non-Differential** out of the **_Type_** column as the different boundaries of two matrices?

**Comment by mdozmorov** [comment]
Differential column = Differential will indicate strong, likely biologically meaningful differences. Type column has more fine-grained differences of actual TADs, please, see our [paper](https://doi.org/10.3389/fgene.2020.00158) for details.

**Comment by esroom** [comment]
Thank you for your quick reply.

**Comment by mdozmorov** [comment]
Closing as resolved. Feel free to ask in this thread, if any other questions.
