### ISSUE TITLE
Run TADCompare at once for the whole genome

### ISSUE THREAD

**Issue by bostanict** [dozmorovlab/TADCompare#8]
Hi,

I checked the straw and it seems it just extracts data for the 2 pairs of chr we provide. but is there any way you can suggest running the TADCompare for all chrs at once and not one by one? I know we can do bash scripting but I want to know if there is any implementation in TADCompatre,

Thanks

**Comment by mdozmorov** [comment]
It would be a loop in R, or, in bash, Rscript.
