### ISSUE TITLE
Resolution does not work

### ISSUE THREAD

**Issue by tanjimin** [dozmorovlab/TADCompare#9]
Hi I tried to ran TADCompare with different resolution (10kb - 50kb), but each time it gives me the same results.

To be exact these are the command that I ran separately:
TD_Compare <- TADCompare(chr1_A, chr1_B, resolution = 10000);
TD_Compare <- TADCompare(chr1_A, chr1_B, resolution = 20000);
TD_Compare <- TADCompare(chr1_A, chr1_B, resolution = 50000);
I got exactly 386 entries in TD_Compare$TAD_Frame each time. Let me know if you can repeat this issue. Thanks!

**Comment by mdozmorov** [comment]
That's strange. @cresswellkg, can you help to look into it? It is on my list to look as well.

**Comment by tanjimin** [comment]
Hi any updates? I was able to repeat the problem with your sample code as well.

data("GM12878.40kb.raw.chr2")
data("IMR90.40kb.raw.chr2")
TD_Compare <- TADCompare(GM12878.40kb.raw.chr2, IMR90.40kb.raw.chr2, resolution = 10000) # change resolution
TAD <- TD_Compare$TAD_Frame

**Comment by mdozmorov** [comment]
Resolution is an obsolete parameter. It was used to calculate the distance between differential boundaries, to convert from bin size to the actual number of bases. This distance is no longer returned, so changing resolution won't affect the results. Unless Kellen corrects me, I'll clarify that resolution is obsolete, remove its mentions from the vignette, and update BioC. In a meantime, ignore this parameter.

**Comment by tanjimin** [comment]
This does not make sense to me. The program has no way of knowing what resolution the input is at. I think TADs needs to be called at a range around 1M bases, and I don't know how you can do this without the resolution parameter. Unless you assume a certain resolution. In that case, do you know what would be the assumed resolution?

**Comment by mdozmorov** [comment]
Genomic coordinates of each bin are obtained from the data - check `as.numeric(colnames(GM12878.40kb.raw.chr2))`. TADcompare operates on bins.  Change the `window_size` parameter, it'll change the number of bins in which TAD differences will be estimated. If you have 50kb data and want to limit your TADs to no more than 1Mb, then use `window_size` = 1Mb/50kb = 20. Does it help?

**Comment by tanjimin** [comment]
Thank you for the explanation! Yes, that is extremely helpful. 

So `window_size` is the parameter for setting the range (num of bins) for TAD. Right now it defaults to 15 which corresponds to 150kb TAD under 10kb resolution. I think that is the source of issue in my reproduction right now. I didn't see this parameter in README, so maybe you can document it there as its quite important.  Also the link to TADCompare vignette is not working and I had to search it on Google.

In addition, I just verified that changing `window_size` changes the number of events detected. Thank you very much!

**Comment by mdozmorov** [comment]
Just to clarify, for 10kb resolution data, you may want to set `window_size` to 100. That's because you want to scan a 1Mb window, and it corresponds to 100 10kb-sized bins.  This window will slide across the diagonal and return genomic coordinates where boundary scores are different.  I'll plan to clarify that and fix the vignette.

**Comment by tanjimin** [comment]
Yes I think it is clear that `window_size = TAD_in_basepair / resolution`. Thank you for quick response!
